
services:
  api:
    build:
      context: ./backend
      args:
        UV_EXTRA_ARGS: ""
    container_name: exactum_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app:z
      - /app/.venv 
    user: root
    command: ["flask", "--app", "run:app", "run", "--host=0.0.0.0", "--port=5000", "--debug"]

  db:
    image: postgres:15
    container_name: exactum_db
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
