[pytest]

pythonpath = .

# 1. Defines the default arguments that will always be executed.
addopts = -v --tb=short --cov=app --cov-report=term-missing

# 2. Indicates where pytest should look for tests.
testpaths = tests

# 3. Registers custom markers to avoid warning alerts.
markers =
    unit: Quick and isolated unit tests.
    functional: Integration tests/routes that utilize the PostgreSQL database.

# 4. Configures which file and function patterns pytest should read.
python_files = test_*.py
python_classes = Test*
python_functions = test_*