DEFAULT_ROLES = {
    "administrator": [
        "product:view",
        "product:create",
        "product:update",
        "product:delete",
        "sale:view",
        "sale:create",
        "sale:cancel",
        "user:view",
        "user:create",
        "user:update",
        "user:delete",
        "profile:view",
        "profile:update",
        "tenant:view",
        "tenant:update",
        "analytics:view",
        "inventory:view",
        "inventory:update",
        "goal:view",
        "goal:create",
        "goal:update",
        "goal:delete",
        "rbac:view",
    ],
    "sales_manager": [
        "product:view",
        "sale:view",
        "sale:create",
        "sale:cancel",
        "analytics:view",
        "goal:view",
        "goal:create",
        "goal:update",
        "inventory:view",
        "profile:view",
        "profile:update",
    ],
    "seller": [
        "product:view",
        "sale:view",
        "sale:create",
        "goal:view",
        "profile:view",
        "profile:update",
    ],
    "stock_clerk": [
        "product:view",
        "product:create",
        "product:update",
        "inventory:view",
        "inventory:update",
        "profile:view",
        "profile:update",
    ],
}
