DEFAULT_ROLES = {
    "administrador": [
        "product:view",
        "product:create",
        "product:update",
        "product:delete",
        "sale:view",
        "sale:create",
        "sale:cancel",
        "user:view",
        "user:create",
        "user:update",
        "user:delete",
        "profile:view",
        "profile:update",
        "tenant:view",
        "tenant:update",
        "analytics:view",
        "inventory:view",
        "inventory:update",
        "goal:view",
        "goal:create",
        "goal:update",
        "goal:delete",
        "rbac:view",
        "logs:view",
    ],
    "gerente_de_vendas": [
        "product:view",
        "sale:view",
        "sale:create",
        "sale:cancel",
        "analytics:view",
        "goal:view",
        "goal:create",
        "goal:update",
        "inventory:view",
        "profile:view",
        "profile:update",
    ],
    "vendedor": [
        "product:view",
        "sale:view",
        "sale:create",
        "goal:view",
        "profile:view",
        "profile:update",
    ],
    "estoquista": [
        "product:view",
        "product:create",
        "product:update",
        "inventory:view",
        "inventory:update",
        "profile:view",
        "profile:update",
    ],
    "acesso_restrito": [
        "profile:view",
        "profile:update",
    ],
}
