"""rename id_sale in ItemSale table

Revision ID: 135f5e29ff87
Revises: 68130ad3d4d6
Create Date: 2026-05-05 00:08:58.980566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135f5e29ff87'
down_revision = '68130ad3d4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sale', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('items_sales_id_vendas_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales', ['id_sale'], ['id'])
        batch_op.drop_column('id_vendas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_vendas', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('items_sales_id_vendas_fkey'), 'sales', ['id_vendas'], ['id'])
        batch_op.drop_column('id_sale')

    # ### end Alembic commands ###
