"""feat: add mixin to insert soft delete in product table

Revision ID: 167edc412342
Revises: cd7b086e9662
Create Date: 2026-07-15 17:31:24.526517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167edc412342'
down_revision = 'cd7b086e9662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
