"""feat: add user_uuid and tenant_uuid in audit and platform table

Revision ID: 25e7da13b636
Revises: 5ebaef95793e
Create Date: 2026-07-07 22:16:26.655141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e7da13b636'
down_revision = '5ebaef95793e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_uuid', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('user_uuid', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_uuid'), ['tenant_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_uuid'), ['user_uuid'], unique=False)

    with op.batch_alter_table('platform_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_uuid', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('user_uuid', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_platform_events_tenant_uuid'), ['tenant_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_events_user_uuid'), ['user_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_events_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_platform_events_tenant_uuid'))
        batch_op.drop_column('user_uuid')
        batch_op.drop_column('tenant_uuid')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_uuid'))
        batch_op.drop_column('user_uuid')
        batch_op.drop_column('tenant_uuid')

    # ### end Alembic commands ###
