"""update price name in Sale and ItemSale tables

Revision ID: 336206cb2b5c
Revises: ea45f824363a
Create Date: 2026-05-05 03:14:01.158780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336206cb2b5c'
down_revision = 'ea45f824363a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price_item')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('total_price')

    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_item', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('item_price')

    # ### end Alembic commands ###
