"""empty message

Revision ID: 38d4c3b6bb85
Revises: 4acace789867
Create Date: 2026-04-20 19:48:41.193845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d4c3b6bb85'
down_revision = '4acace789867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.create_unique_constraint(None, ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
