"""remove_permission_table

Revision ID: 444f6e56665c
Revises: cf17f43ad452
Create Date: 2026-06-25 21:46:52.886954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444f6e56665c'
down_revision = 'cf17f43ad452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('module')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
