"""add sku and category in products

Revision ID: 4acace789867
Revises: 52ddf21214be
Create Date: 2026-03-27 22:02:45.654652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acace789867'
down_revision = '52ddf21214be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
