"""fix: tenant_id not null

Revision ID: 52ddf21214be
Revises: ddcab84cc44e
Create Date: 2026-03-13 20:08:05.951246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ddf21214be'
down_revision = 'ddcab84cc44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
