"""feat: add category and product uuid in ItemSale

Revision ID: 5ad2a990292e
Revises: c9b91cd62efd
Create Date: 2026-08-14 02:00:46.917773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad2a990292e'
down_revision = 'c9b91cd62efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_uuid', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['product_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category')
        batch_op.drop_column('product_uuid')

    # ### end Alembic commands ###
