"""add password_reset  in users table

Revision ID: 68130ad3d4d6
Revises: b05200acb4ae
Create Date: 2026-04-28 21:37:28.983891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68130ad3d4d6'
down_revision = 'b05200acb4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset')

    # ### end Alembic commands ###
