"""add fantasy name in tenant table

Revision ID: 6c4a2d558998
Revises: 38d4c3b6bb85
Create Date: 2026-04-20 20:21:23.633300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4a2d558998'
down_revision = '38d4c3b6bb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fantasy_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('fantasy_name')

    # ### end Alembic commands ###
