"""add channel column in sale and item sale table

Revision ID: 6de232d53435
Revises: ff991b1be948
Create Date: 2026-05-21 22:47:45.949360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de232d53435'
down_revision = 'ff991b1be948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('channel')

    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
