"""add created_at in ItemSale table

Revision ID: 9319a8a3a1ad
Revises: 336206cb2b5c
Create Date: 2026-05-05 15:47:07.682418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9319a8a3a1ad'
down_revision = '336206cb2b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
