"""add quantity_items in sales table

Revision ID: b05200acb4ae
Revises: d8ea3069de4c
Create Date: 2026-04-25 21:16:53.647498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05200acb4ae'
down_revision = 'd8ea3069de4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_items', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('quantity_items')

    # ### end Alembic commands ###
