"""remove ip address and entity id from audit logs table

Revision ID: cd7b086e9662
Revises: 25e7da13b636
Create Date: 2026-07-09 15:27:58.673920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7b086e9662'
down_revision = '25e7da13b636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('entity_id')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.BIGINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
