"""update ItemSale and Sale tables

Revision ID: ea45f824363a
Revises: 135f5e29ff87
Create Date: 2026-05-05 03:10:37.587916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea45f824363a'
down_revision = '135f5e29ff87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_item', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('sale_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('items_sales_id_sale_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('items_sales_id_user_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('items_sales_id_tenant_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sales', ['sale_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('id_user')
        batch_op.drop_column('id_tenant')
        batch_op.drop_column('id_sale')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('price_total')

    with op.batch_alter_table('items_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sale', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_tenant', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('items_sales_id_tenant_fkey'), 'tenants', ['id_tenant'], ['id'])
        batch_op.create_foreign_key(batch_op.f('items_sales_id_user_fkey'), 'users', ['id_user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('items_sales_id_sale_fkey'), 'sales', ['id_sale'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('sale_id')
        batch_op.drop_column('price_item')

    # ### end Alembic commands ###
