"""add global_min_stock and corporate_email in tenant table

Revision ID: ff991b1be948
Revises: efd202d8d73f
Create Date: 2026-05-09 19:31:54.027286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff991b1be948'
down_revision = 'efd202d8d73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_min_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('corporate_email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['corporate_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('corporate_email')
        batch_op.drop_column('global_min_stock')

    # ### end Alembic commands ###
