name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /etc/opt/exactum-api

            git fetch origin
            git reset --hard origin/main

            docker compose -f docker-compose.prod.yml build

            docker compose -f docker-compose.prod.yml up -d db

            docker compose -f docker-compose.prod.yml run --rm api flask db upgrade

            docker compose -f docker-compose.prod.yml up -d --build

            docker image prune -f